/* InkDeck 3.10 games. ES5 only for the Kindle Mesquite engine. */
(function(){
  var byId=function(id){return document.getElementById(id);};
  function el(tag,cls,text){var n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;}
  function hacked(){return !!(window.InkDeck&&InkDeck.isHacked&&InkDeck.isHacked());}
  function shuffle(a){var i,j,t;for(i=a.length-1;i>0;i--){j=Math.floor(Math.random()*(i+1));t=a[i];a[i]=a[j];a[j]=t;}return a;}

  /* Mahjong Connect: identical tiles may be joined using at most two turns. */
  var mj={board:[],selected:-1,left:0,moves:0,over:false},mjSymbols=['●','■','▲','◆','★','☀','☂','♣','♠','♥','♦','☯','月','山','水','火','木','金','土','龍'];
  function mjNew(){var a=[],i;for(i=0;i<20;i++){a.push(i);a.push(i);a.push(i);a.push(i);}shuffle(a);mj.board=a;mj.selected=-1;mj.left=80;mj.moves=0;mj.over=false;mjRender();}
  function mjPos(i){return {r:Math.floor(i/10)+1,c:i%10+1};}
  function mjAt(r,c){if(r<1||r>8||c<1||c>10)return -1;return mj.board[(r-1)*10+c-1];}
  function mjCan(a,b){var start=mjPos(a),target=mjPos(b),dirs=[[1,0],[-1,0],[0,1],[0,-1]],q=[],seen={},d,nr,nc,key,cur,turns;if(a===b)return false;for(d=0;d<4;d++)q.push({r:start.r,c:start.c,dir:d,turns:0});while(q.length){cur=q.shift();nr=cur.r+dirs[cur.dir][0];nc=cur.c+dirs[cur.dir][1];if(nr<0||nr>9||nc<0||nc>11)continue;if(nr===target.r&&nc===target.c)return true;if(mjAt(nr,nc)>=0)continue;key=nr+','+nc+','+cur.dir;if(seen[key]!==undefined&&seen[key]<=cur.turns)continue;seen[key]=cur.turns;q.push({r:nr,c:nc,dir:cur.dir,turns:cur.turns});for(d=0;d<4;d++)if(d!==cur.dir){turns=cur.turns+1;if(turns<=2)q.push({r:nr,c:nc,dir:d,turns:turns});}}return false;}
  function mjPair(){var i,j;for(i=0;i<80;i++)if(mj.board[i]>=0)for(j=i+1;j<80;j++)if(mj.board[i]===mj.board[j]&&(hacked()||mjCan(i,j)))return [i,j];return null;}
  function mjTap(i){if(mj.over||mj.board[i]<0)return;if(mj.selected<0){mj.selected=i;mjRender();return;}if(mj.selected===i){mj.selected=-1;mjRender();return;}mj.moves++;if(mj.board[mj.selected]===mj.board[i]&&(hacked()||mjCan(mj.selected,i))){mj.board[mj.selected]=-1;mj.board[i]=-1;mj.left-=2;mj.selected=-1;if(!mj.left){mj.over=true;byId('mahjongStatus').textContent='WYGRANA · Ruchy: '+mj.moves;}else if(!mjPair())shuffleRemaining();}else{byId('mahjongStatus').textContent='Nie można połączyć tych płytek';mj.selected=i;}mjRender();}
  function shuffleRemaining(){var spots=[],vals=[],i;for(i=0;i<80;i++)if(mj.board[i]>=0){spots.push(i);vals.push(mj.board[i]);}shuffle(vals);for(i=0;i<spots.length;i++)mj.board[spots[i]]=vals[i];}
  function mjRender(){var b=byId('mahjongBoard'),i,c,size=Math.max(39,Math.min(55,Math.floor((window.innerWidth-22)/10)));b.innerHTML='';b.style.width=(size*10+6)+'px';for(i=0;i<80;i++){c=el('button','mahjongTile'+(i===mj.selected?' selected':''),mj.board[i]<0?'':mjSymbols[mj.board[i]]);c.style.width=size+'px';c.style.height=size+'px';c.style.lineHeight=(size-4)+'px';c.setAttribute('data-i',i);if(mj.board[i]<0)c.className+=' empty';c.onclick=function(){mjTap(parseInt(this.getAttribute('data-i'),10));};b.appendChild(c);}if(!mj.over&&byId('mahjongStatus').textContent.indexOf('Nie można')!==0)byId('mahjongStatus').textContent='Pary: '+(mj.left/2)+' · Ruchy: '+mj.moves;}
  byId('mahjongNew').onclick=mjNew;byId('mahjongHint').onclick=function(){var p=mjPair();if(!p){shuffleRemaining();mjRender();return;}mj.selected=p[0];mjRender();byId('mahjongStatus').textContent='Podpowiedź: zaznaczona płytka ma parę';};

  /* Chińczyk: 2-4 local players, four pawns each, 40-field track and home. */
  var ludo={players:2,pawns:[],turn:0,dice:0,rolled:false,over:false},ludoNames=['BIAŁY','SZARY','CZARNY','PASKI'],ludoMarks=['○','●','■','◆'];
  function ludoNew(){var p,i;ludo.players=parseInt(byId('ludoPlayers').value,10)||2;ludo.pawns=[];for(p=0;p<ludo.players;p++){ludo.pawns[p]=[];for(i=0;i<4;i++)ludo.pawns[p][i]=-1;}ludo.turn=0;ludo.dice=0;ludo.rolled=false;ludo.over=false;byId('ludoDice').textContent='—';ludoRender();}
  function ludoGlobal(p,pos){return (p*10+pos)%40;}
  function ludoMovable(p,i,d){var pos=ludo.pawns[p][i];if(hacked())return pos<44;if(pos<0)return d===6;if(pos>=40)return pos+d<=44;return pos+d<=44;}
  function ludoMove(i){var p=ludo.turn,d=ludo.dice,pos=ludo.pawns[p][i],np,op,j,g;if(!ludo.rolled||!ludoMovable(p,i,d))return;if(hacked()&&d<1)d=6;if(pos<0)np=0;else np=pos+d;ludo.pawns[p][i]=np;if(np<40){g=ludoGlobal(p,np);for(op=0;op<ludo.players;op++)if(op!==p)for(j=0;j<4;j++)if(ludo.pawns[op][j]>=0&&ludo.pawns[op][j]<40&&ludoGlobal(op,ludo.pawns[op][j])===g)ludo.pawns[op][j]=-1;}if(ludo.pawns[p][0]===44&&ludo.pawns[p][1]===44&&ludo.pawns[p][2]===44&&ludo.pawns[p][3]===44){ludo.over=true;byId('ludoStatus').textContent='WYGRYWA: '+ludoNames[p];}else if(d!==6&&!hacked())ludo.turn=(ludo.turn+1)%ludo.players;ludo.rolled=false;ludo.dice=0;byId('ludoDice').textContent='—';ludoRender();}
  function ludoRoll(){if(ludo.over||ludo.rolled)return;ludo.dice=1+Math.floor(Math.random()*6);ludo.rolled=true;byId('ludoDice').textContent=String(ludo.dice);ludoRender();var i,any=false;for(i=0;i<4;i++)if(ludoMovable(ludo.turn,i,ludo.dice))any=true;if(!any){ludo.rolled=false;setTimeout(function(){ludo.turn=(ludo.turn+1)%ludo.players;byId('ludoDice').textContent='—';ludoRender();},500);}}
  function ludoTrackCoords(){var a=[],r,c;for(c=5;c<=10;c++)a.push([0,c]);for(r=1;r<=10;r++)a.push([r,10]);for(c=9;c>=0;c--)a.push([10,c]);for(r=9;r>=0;r--)a.push([r,0]);for(c=1;c<=4;c++)a.push([0,c]);return a;}
  function ludoRender(){var b=byId('ludoBoard'),table=el('table','ludoTable'),coords=ludoTrackCoords(),lookup={},r,c,row,td,p,i,pos,g,txt,moves=byId('ludoMoves'),btn;for(i=0;i<coords.length;i++)lookup[coords[i][0]+','+coords[i][1]]=i;for(r=0;r<11;r++){row=table.insertRow(-1);for(c=0;c<11;c++){td=row.insertCell(-1);td.className=lookup[r+','+c]!==undefined?'ludoCell track':'ludoCell';if((r<4&&c<4)||(r<4&&c>6)||(r>6&&c<4)||(r>6&&c>6))td.className+=' base';td.textContent='';}}for(p=0;p<ludo.players;p++)for(i=0;i<4;i++){pos=ludo.pawns[p][i];if(pos>=0&&pos<40){g=ludoGlobal(p,pos);r=coords[g][0];c=coords[g][1];txt=table.rows[r].cells[c].textContent;table.rows[r].cells[c].textContent=txt+ludoMarks[p]+(i+1);}else if(pos>=40)table.rows[5].cells[3+p].textContent+=ludoMarks[p]+(i+1);}b.innerHTML='';b.appendChild(table);moves.innerHTML='';if(!ludo.over){byId('ludoStatus').textContent='Ruch: '+ludoNames[ludo.turn]+(hacked()?' · HACKED':'');if(ludo.rolled)for(i=0;i<4;i++)if(ludoMovable(ludo.turn,i,ludo.dice)){btn=el('button','ludoPawnButton',ludoMarks[ludo.turn]+' PIONEK '+(i+1));btn.setAttribute('data-i',i);btn.onclick=function(){ludoMove(parseInt(this.getAttribute('data-i'),10));};moves.appendChild(btn);}}}
  byId('ludoPlayers').value=InkDeck.settingGet?InkDeck.settingGet('ludoplayers','2'):'2';
  byId('ludoRoll').onclick=ludoRoll;byId('ludoNew').onclick=ludoNew;byId('ludoPlayers').onchange=function(){if(InkDeck.settingSet)InkDeck.settingSet('ludoplayers',this.value);ludoNew();};

  /* Paper soccer inspired by Kurnik: 10x8 grid, unused edges and rebounds. */
  var soccer={x:5,y:4,edges:{},turn:0,over:false},soccerDirs=[[-1,-1],[0,-1],[1,-1],[-1,0],[1,0],[-1,1],[0,1],[1,1]];
  function soccerKey(x1,y1,x2,y2){var a=x1+','+y1+'-'+x2+','+y2,b=x2+','+y2+'-'+x1+','+y1;return a<b?a:b;}
  function soccerDegree(x,y){var k,n=0,needle1=x+','+y+'-',needle2='-'+x+','+y;for(k in soccer.edges)if(soccer.edges.hasOwnProperty(k)&&(k.indexOf(needle1)===0||k.indexOf(needle2)>=0))n++;return n;}
  function soccerValid(x,y){if(y===-1||y===9)return x===5;return x>=0&&x<=10&&y>=0&&y<=8;}
  function soccerMove(x,y){var dx=Math.abs(x-soccer.x),dy=Math.abs(y-soccer.y),key,bounce;if(soccer.over||!soccerValid(x,y))return;if(!hacked()&&(dx>1||dy>1||(!dx&&!dy)))return;key=soccerKey(soccer.x,soccer.y,x,y);if(!hacked()&&soccer.edges[key])return;if(!hacked()&&((soccer.x===0&&x===0)||(soccer.x===10&&x===10)||(soccer.y===0&&y===0)||(soccer.y===8&&y===8)))return;bounce=soccerDegree(x,y)>0||x===0||x===10||y===0||y===8;soccer.edges[key]=1;soccer.x=x;soccer.y=y;if(y===-1||y===9){soccer.over=true;byId('soccerStatus').textContent='GOL! Wygrywają '+(y===-1?'BIALI':'CZARNI');}else if(!bounce)soccer.turn=1-soccer.turn;soccerRender();}
  function soccerNew(){soccer={x:5,y:4,edges:{},turn:0,over:false};soccerRender();}
  function soccerPoint(x,y,w,h){return {x:26+x*(w-52)/10,y:y<0?0:(y>8?h:26+y*(h-52)/8)};}
  function soccerRender(){var box=byId('soccerBoard'),canvas=byId('soccerCanvas'),nodes=byId('soccerNodes'),w=Math.min(610,window.innerWidth-12),h=Math.min(610,window.innerHeight-145),ctx,k,parts,a,b,p1,p2,x,y,n,p;box.style.width=w+'px';box.style.height=h+'px';canvas.width=w;canvas.height=h;canvas.style.width=w+'px';canvas.style.height=h+'px';ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#000';ctx.lineWidth=3;ctx.strokeRect(26,26,w-52,h-52);ctx.strokeRect(w/2-(w-52)/10,0,2*(w-52)/10,26);ctx.strokeRect(w/2-(w-52)/10,h-26,2*(w-52)/10,26);ctx.lineWidth=2;for(k in soccer.edges)if(soccer.edges.hasOwnProperty(k)){parts=k.split('-');a=parts[0].split(',');b=parts[1].split(',');p1=soccerPoint(+a[0],+a[1],w,h);p2=soccerPoint(+b[0],+b[1],w,h);ctx.beginPath();ctx.moveTo(p1.x,p1.y);ctx.lineTo(p2.x,p2.y);ctx.stroke();}nodes.innerHTML='';for(y=-1;y<=9;y++)for(x=0;x<=10;x++)if(soccerValid(x,y)){p=soccerPoint(x,y,w,h);n=el('button','soccerNode'+(x===soccer.x&&y===soccer.y?' ball':''),x===soccer.x&&y===soccer.y?'●':'');n.style.left=(p.x-10)+'px';n.style.top=(p.y-10)+'px';n.setAttribute('data-x',x);n.setAttribute('data-y',y);n.onclick=function(){soccerMove(+this.getAttribute('data-x'),+this.getAttribute('data-y'));};nodes.appendChild(n);}if(!soccer.over)byId('soccerStatus').textContent='PIŁKA · RUCH '+(soccer.turn?'CZARNYCH':'BIAŁYCH')+(hacked()?' · HACKED':'');}
  byId('soccerNew').onclick=soccerNew;

  var oldRender=InkDeck.renderGame;InkDeck.renderGame=function(id){if(oldRender)oldRender(id);if(id==='mahjongconnect'&&!mj.board.length)mjNew();else if(id==='ludo'&&!ludo.pawns.length)ludoNew();else if(id==='papersoccer')soccerRender();};
  InkDeck.extraHack=function(id){var p;if(id==='mahjongconnect'){p=mjPair();if(p){mj.board[p[0]]=-1;mj.board[p[1]]=-1;mj.left-=2;mjRender();}}else if(id==='ludo'){if(!ludo.rolled){ludo.dice=6;ludo.rolled=true;byId('ludoDice').textContent='6';ludoRender();}}else if(id==='papersoccer'){soccer.turn=0;soccerRender();}else if(id==='sudoku'){byId('sudokuHint').click();}else if(id==='nonogram'){byId('nonogramStatus').textContent='HACKED: błędy są wyłączone';}};
  var rulesTab=document.querySelector('.hacketTabs [data-hacket="rules"]');
  if(rulesTab)rulesTab.addEventListener('click',function(){var box=byId('hacketContent');if(box.innerHTML.indexOf('<h3>Mahjong Connect</h3>')>=0)return;box.innerHTML+='<h3>Mahjong Connect</h3><p>Usuń wszystkie pary jednakowych płytek. Droga między nimi może przebiegać przez puste pola i skręcić najwyżej dwa razy.</p><h3>Chińczyk</h3><p>Gra dla 2–4 osób. Szóstka wyprowadza pionek z bazy i daje dodatkowy rzut. Zbicie odsyła pionek rywala do bazy. Wygrywa gracz, który doprowadzi cztery pionki do domu.</p><h3>Piłka na kartce</h3><p>Rysuj odcinki między sąsiednimi punktami. Nie można użyć tej samej linii ponownie. Dotarcie do brzegu lub wcześniej odwiedzonego punktu daje odbicie i kolejny ruch. Gol kończy mecz.</p>';});
  window.addEventListener('resize',function(){if(byId('papersoccer').className.indexOf('active')>=0)soccerRender();});
}());
