/* Lightweight built-in games kept separate from the legacy Kindle UI code. */
(function(){
  var byId=function(id){return document.getElementById(id);}, el=function(tag,cls,txt){var n=document.createElement(tag);if(cls)n.className=cls;if(txt!==undefined)n.textContent=txt;return n;};
  var snake={body:[],dir:[1,0],food:0,timer:null,over:false,score:0};
  function snakeNew(){clearInterval(snake.timer);snake.body=[78,77,76];snake.dir=[1,0];do{snake.food=Math.floor(Math.random()*144);}while(snake.body.indexOf(snake.food)>=0);snake.over=false;snake.score=0;snakeRender();snake.timer=setInterval(snakeStep,650);}
  function squareCellSize(board,cols,maxSize){var top=board.getBoundingClientRect().top,maxW=window.innerWidth-24,maxH=window.innerHeight-top-12,size=Math.min(maxSize,maxW,maxH);return Math.max(18,Math.floor((size-8)/cols));}
  function snakeRender(){var b=byId('snakeBoard'),i,c,cell=squareCellSize(b,12,540),size=cell*12;b.innerHTML='';b.style.width=(size+8)+'px';b.style.height=(size+8)+'px';for(i=0;i<144;i++){c=el('div','snakeCell'+(snake.body.indexOf(i)>=0?' snakeBody':'')+(i===snake.food?' snakeFood':''),i===snake.food?'●':'');c.style.width=cell+'px';c.style.height=cell+'px';c.style.lineHeight=cell+'px';b.appendChild(c);}byId('snakeStatus').textContent='Punkty: '+snake.score+(snake.over?' — koniec gry':'');}
  function snakeTurn(x,y){if(snake.dir[0]+x===0&&snake.dir[1]+y===0)return;snake.dir=[x,y];}
  function snakeStep(){var head=snake.body[0],x=head%12+snake.dir[0],y=Math.floor(head/12)+snake.dir[1],next;if(snake.over)return;if(InkDeck.isHacked&&InkDeck.isHacked()){if(x<0)x=11;if(x>11)x=0;if(y<0)y=11;if(y>11)y=0;}next=y*12+x;if(x<0||x>11||y<0||y>11||(!(InkDeck.isHacked&&InkDeck.isHacked())&&snake.body.indexOf(next)>=0)){snake.over=true;clearInterval(snake.timer);snakeRender();return;}snake.body.unshift(next);if(next===snake.food){snake.score++;do{snake.food=Math.floor(Math.random()*144);}while(snake.body.indexOf(snake.food)>=0);}else snake.body.pop();snakeRender();}
  byId('snakeNew').onclick=snakeNew;byId('snakeUp').onclick=function(){snakeTurn(0,-1);};byId('snakeDown').onclick=function(){snakeTurn(0,1);};byId('snakeLeft').onclick=function(){snakeTurn(-1,0);};byId('snakeRight').onclick=function(){snakeTurn(1,0);};

  var sudoku={grid:[],given:[],solution:[],selected:-1,level:3,over:false,errors:0,hints:0};
  function sudokuValid(a,pos,n){var r=Math.floor(pos/9),c=pos%9,i,j;for(i=0;i<9;i++)if(a[r*9+i]===n||a[i*9+c]===n)return false;for(i=Math.floor(r/3)*3;i<Math.floor(r/3)*3+3;i++)for(j=Math.floor(c/3)*3;j<Math.floor(c/3)*3+3;j++)if(a[i*9+j]===n)return false;return true;}
  function sudokuSolve(a){var p=a.indexOf(0),n,k,nums=[1,2,3,4,5,6,7,8,9];if(p<0)return true;for(k=8;k>0;k--){n=Math.floor(Math.random()*(k+1));var t=nums[k];nums[k]=nums[n];nums[n]=t;}for(k=0;k<9;k++){n=nums[k];if(sudokuValid(a,p,n)){a[p]=n;if(sudokuSolve(a))return true;a[p]=0;}}return false;}
  function sudokuNew(){var a=[],i,remove=[27,34,40,46,52,57][parseInt(byId('sudokuLevel').value,10)-1];for(i=0;i<81;i++)a[i]=0;sudokuSolve(a);sudoku.solution=a.slice(0);sudoku.grid=a.slice(0);sudoku.given=[];for(i=0;i<81;i++)sudoku.given[i]=true;var cells=[];for(i=0;i<81;i++)cells.push(i);for(i=80;i>0;i--){var j=Math.floor(Math.random()*(i+1)),q=cells[i];cells[i]=cells[j];cells[j]=q;}for(i=0;i<remove;i++){sudoku.grid[cells[i]]=0;sudoku.given[cells[i]]=false;}sudoku.selected=-1;sudoku.over=false;sudoku.errors=0;sudoku.hints=0;sudokuRender();}
  function sudokuStatus(message){byId('sudokuStatus').textContent=message||('Błędy: '+sudoku.errors+' · Podpowiedzi: '+sudoku.hints);}
  function sudokuNumber(n){var p=sudoku.selected;if(p<0||sudoku.given[p]||sudoku.over)return;if(n!==sudoku.solution[p]&&!(InkDeck.isHacked&&InkDeck.isHacked())){sudoku.errors++;sudokuStatus('BŁĄD! Błędy: '+sudoku.errors);return;}sudoku.grid[p]=n;if(sudokuCheck()){sudoku.over=true;sudokuStatus('Rozwiązane! Błędy: '+sudoku.errors);}else sudokuStatus();sudokuRender();}
  function sudokuBuildKeys(){var keys=byId('sudokuKeys'),i,c;if(keys.children.length)return;for(i=1;i<=9;i++){c=el('button','',String(i));c.setAttribute('data-n',i);c.onclick=function(){sudokuNumber(+this.getAttribute('data-n'));};keys.appendChild(c);}c=el('button','sudokuErase','⌫');c.onclick=function(){if(sudoku.selected>=0&&!sudoku.given[sudoku.selected])sudoku.grid[sudoku.selected]=0;sudokuRender();};keys.appendChild(c);}
  function sudokuRender(){var b=byId('sudokuBoard'),i,c,cell=squareCellSize(b,9,504),size=cell*9;b.innerHTML='';b.style.width=(size+6)+'px';b.style.height=(size+6)+'px';for(i=0;i<81;i++){c=el('button','sudokuCell'+(sudoku.given[i]?' given':'')+(sudoku.selected===i?' selected':''),sudoku.grid[i]||'');c.style.width=cell+'px';c.style.height=cell+'px';c.style.lineHeight=(cell-2)+'px';c.setAttribute('data-i',i);c.onclick=function(){sudoku.selected=+this.getAttribute('data-i');sudokuRender();};b.appendChild(c);}sudokuBuildKeys();if(!sudoku.over&&byId('sudokuStatus').textContent.indexOf('BŁĄD!')!==0)sudokuStatus();}
  function sudokuCheck(){var i,r,c,n;for(i=0;i<81;i++){n=sudoku.grid[i];if(!n)return false;r=Math.floor(i/9);c=i%9;for(var j=0;j<9;j++)if(j!==c&&sudoku.grid[r*9+j]===n)return false;for(j=0;j<9;j++)if(j!==r&&sudoku.grid[j*9+c]===n)return false;for(var y=Math.floor(r/3)*3;y<Math.floor(r/3)*3+3;y++)for(var x=Math.floor(c/3)*3;x<Math.floor(c/3)*3+3;x++)if((y!==r||x!==c)&&sudoku.grid[y*9+x]===n)return false;}return true;}
  byId('sudokuNew').onclick=sudokuNew;byId('sudokuLevel').onchange=function(){InkDeck.settingSet('sudokulevel',this.value);sudokuNew();};byId('sudokuLevel').value=InkDeck.settingGet('sudokulevel','3');byId('sudokuHint').onclick=function(){var level=parseInt(byId('sudokuLevel').value,10),empty=[],i,p;if(level>2&&!(InkDeck.isHacked&&InkDeck.isHacked())){sudokuStatus('Podpowiedzi są tylko na poziomie 1 i 2.');return;}for(i=0;i<81;i++)if(!sudoku.given[i]&&!sudoku.grid[i])empty.push(i);if(!empty.length)return;p=empty[Math.floor(Math.random()*empty.length)];sudoku.grid[p]=sudoku.solution[p];sudoku.selected=p;sudoku.hints++;if(sudokuCheck()){sudoku.over=true;sudokuStatus('Rozwiązane! Błędy: '+sudoku.errors);}else sudokuStatus();sudokuRender();};

  var puzzles={heart:['01110','11111','11111','01110','00100'],smile:['00111100','01000010','10100101','10000001','10100101','10011001','01000010','00111100'],house:['00011000','00111100','01111110','11111111','11011011','11011011','11011011','11111111'],fish:['0001100000','0011110000','1111111000','1111111110','1111111111','1111111000','0011110000','0001100000','0001100000','0010010000'],rocket:['0000010000','0000110000','0001110000','0011111000','0111111100','1111111110','1111111110','0001110000','0010101000','0110001100']},nonogram={name:'heart',grid:[],sol:[],won:false,errors:0};
  function clues(a){var out=[],n=0,i;for(i=0;i<a.length;i++){if(a[i])n++;else if(n){out.push(n);n=0;}}if(n)out.push(n);return out.length?out:[0];}
  function nonogramNew(){nonogram.name=byId('nonogramPuzzle').value;nonogram.sol=puzzles[nonogram.name].join('').split('').map(function(v){return v==='1'?1:0;});nonogram.grid=nonogram.sol.map(function(){return 0;});nonogram.won=false;nonogram.errors=0;nonogramRender();}
  function nonogramTap(p){var k,win=true;if(nonogram.won)return;if(InkDeck.isHacked&&InkDeck.isHacked()){nonogram.grid[p]=(nonogram.grid[p]+1)%3;byId('nonogramStatus').textContent='NONOGRAM · HACKED';}else if(nonogram.sol[p]){nonogram.grid[p]=nonogram.grid[p]===1?0:1;byId('nonogramStatus').textContent='NONOGRAM · Błędy: '+nonogram.errors;}else if(nonogram.grid[p]!==2){nonogram.grid[p]=2;nonogram.errors++;byId('nonogramStatus').textContent='BŁĄD! Błędy: '+nonogram.errors;}for(k=0;k<nonogram.sol.length;k++)if(nonogram.sol[k]&&nonogram.grid[k]!==1)win=false;nonogram.won=win;nonogramRender();}
  function nonogramRender(){var b=byId('nonogramBoard'),src=puzzles[nonogram.name],n=src.length,r,c,cell,top=[],table,row,holder,col,cellSize=n<=5?62:(n<=8?48:39);b.innerHTML='';for(c=0;c<n;c++){col=[];for(r=0;r<n;r++)col.push(+src[r].charAt(c));top.push(clues(col).join('\n'));}table=el('table','nonogramTable');table.setAttribute('cellspacing','0');row=table.insertRow(-1);holder=row.insertCell(-1);holder.className='nonogramCorner';for(c=0;c<n;c++){holder=row.insertCell(-1);holder.className='nonogramClue topClue';holder.style.width=cellSize+'px';holder.textContent=top[c];}for(r=0;r<n;r++){row=table.insertRow(-1);holder=row.insertCell(-1);holder.className='nonogramClue rowClue';holder.textContent=clues(src[r].split('').map(Number)).join(' ');for(c=0;c<n;c++){var i=r*n+c;holder=row.insertCell(-1);holder.className='nonogramSquare'+(c%5===4?' thickRight':'')+(r%5===4?' thickBottom':'');holder.style.width=cellSize+'px';holder.style.height=cellSize+'px';cell=el('button','nonogramCell '+(nonogram.grid[i]===1?'filled':(nonogram.grid[i]===2?'cross':'')),nonogram.grid[i]===2?'×':'');cell.style.width=cellSize+'px';cell.style.height=cellSize+'px';cell.setAttribute('data-i',i);cell.onclick=function(){nonogramTap(+this.getAttribute('data-i'));};holder.appendChild(cell);}}b.appendChild(table);if(nonogram.won)byId('nonogramStatus').textContent='Ułożone! Błędy: '+nonogram.errors;else if(byId('nonogramStatus').textContent.indexOf('BŁĄD!')!==0)byId('nonogramStatus').textContent='NONOGRAM · Błędy: '+nonogram.errors;}
  byId('nonogramNew').onclick=nonogramNew;byId('nonogramPuzzle').onchange=nonogramNew;

  /* Klondike, draw-one: tableau runs, stock/waste and foundations. */
  var sol={piles:[],found:[[],[],[],[]],stock:[],waste:[],sel:null,moves:0};
  var suits=['♠','♥','♦','♣'];function cardColor(c){return c.suit==='♥'||c.suit==='♦';}function cardText(c){return c.rank===1?'A':c.rank===11?'J':c.rank===12?'Q':c.rank===13?'K':String(c.rank)+c.suit;}
  function solitaireNew(){var deck=[],s,r,i,j,t;for(s=0;s<4;s++)for(r=1;r<=13;r++)deck.push({suit:suits[s],rank:r,up:false});for(i=51;i>0;i--){j=Math.floor(Math.random()*(i+1));t=deck[i];deck[i]=deck[j];deck[j]=t;}sol.piles=[];for(i=0;i<7;i++){sol.piles[i]=deck.splice(0,i+1);sol.piles[i][i].up=true;}sol.stock=deck;sol.waste=[];sol.found=[[],[],[],[]];sol.sel=null;sol.moves=0;solRender();}
  function validRun(p,i){if(!p[i].up)return false;for(var k=i;k<p.length-1;k++)if(!p[k+1].up||p[k].rank!==p[k+1].rank+1||cardColor(p[k])===cardColor(p[k+1]))return false;return true;}
  function solCardNode(card,cls){var n=el('div','playingCard '+cls,card.up?cardText(card):'▧');if(card.up&&cardColor(card))n.className+=' redCard';return n;}
  function solDraw(){if(sol.stock.length){sol.waste.push(sol.stock.pop());sol.waste[sol.waste.length-1].up=true;}else{sol.stock=sol.waste.reverse();sol.waste=[];sol.stock.forEach(function(c){c.up=false;});}sol.sel=null;sol.moves++;solRender();}
  function solRender(){var tb=byId('solitaireTableau'),fb=byId('solitaireFoundations'),i,j,p,node,slot,won=sol.found.every(function(a){return a.length===13;});tb.innerHTML='';fb.innerHTML='';slot=el('button','foundationSlot',sol.stock.length?'TALON':'↻');slot.onclick=solDraw;fb.appendChild(slot);slot=el('button','foundationSlot',sol.waste.length?cardText(sol.waste[sol.waste.length-1]):'—');slot.onclick=function(){if(sol.waste.length){sol.sel={type:'waste'};solRender();}};fb.appendChild(slot);for(i=0;i<4;i++){(function(f){var top=sol.found[f].length?sol.found[f][sol.found[f].length-1]:null,foundation=el('button','foundationSlot',top?cardText(top):suits[f]);foundation.onclick=function(){solToFoundation(f);};fb.appendChild(foundation);})(i);}for(i=0;i<7;i++){p=el('div','solitairePile');p.setAttribute('data-pile',i);p.onclick=function(){solToPile(+this.getAttribute('data-pile'));};for(j=0;j<sol.piles[i].length;j++){node=solCardNode(sol.piles[i][j],'tableauCard'+(sol.sel&&sol.sel.type==='pile'&&sol.sel.pile===i&&sol.sel.index===j?' chosen':''));node.style.marginTop=j?'-58px':'0';node.setAttribute('data-pile',i);node.setAttribute('data-index',j);node.onclick=function(e){var dest=+this.getAttribute('data-pile'),index=+this.getAttribute('data-index');e.stopPropagation();if(sol.sel&&!(sol.sel.type==='pile'&&sol.sel.pile===dest))solToPile(dest);else solSelect(dest,index);};p.appendChild(node);}tb.appendChild(p);}byId('solitaireStatus').textContent=won?'Wygrana!':'Ruchy: '+sol.moves;}
  function solSelect(p,i){if(!sol.piles[p][i].up)return;sol.sel={type:'pile',pile:p,index:i};solRender();}function solSelectedCards(){if(!sol.sel)return[];if(sol.sel.type==='waste')return sol.waste.length?[sol.waste[sol.waste.length-1]]:[];return sol.piles[sol.sel.pile].slice(sol.sel.index);}
  function solToPile(dest){if(!sol.sel||(sol.sel.type==='pile'&&sol.sel.pile===dest))return;var cards=solSelectedCards(),pile=sol.piles[dest],first=cards[0],top=pile[pile.length-1];if(!cards.length||!validRun(sol.sel.type==='pile'?sol.piles[sol.sel.pile]:[first],sol.sel.type==='pile'?sol.sel.index:0))return;if((!top&&first.rank===13)||(top&&top.up&&top.rank===first.rank+1&&cardColor(top)!==cardColor(first))){if(sol.sel.type==='waste')sol.waste.pop();else{sol.piles[sol.sel.pile]=sol.piles[sol.sel.pile].slice(0,sol.sel.index);var old=sol.piles[sol.sel.pile];if(old.length)old[old.length-1].up=true;}pile.push.apply(pile,cards);sol.sel=null;sol.moves++;solRender();}}
  function solToFoundation(f){var c;if(sol.sel&&sol.sel.type==='waste')c=sol.waste[sol.waste.length-1];else if(sol.sel&&sol.sel.type==='pile'&&sol.sel.index===sol.piles[sol.sel.pile].length-1)c=sol.piles[sol.sel.pile][sol.sel.index];if(!c||!c.up)return;var dst=sol.found[f],top=dst[dst.length-1];if(c.suit===suits[f]&&((!top&&c.rank===1)||(top&&c.rank===top.rank+1))){if(sol.sel.type==='waste')sol.waste.pop();else{sol.piles[sol.sel.pile].pop();var p=sol.piles[sol.sel.pile];if(p.length)p[p.length-1].up=true;}dst.push(c);sol.sel=null;sol.moves++;solRender();}}
  /* Pasjans usunięty z interfejsu w 3.9.2. Kod pozostaje nieaktywny dla zgodności zapisów. */

  InkDeck.renderGame=function(id){if(id==='snake'&&!snake.body.length)snakeNew();else if(id==='sudoku'&&!sudoku.grid.length)sudokuNew();else if(id==='nonogram'&&!nonogram.grid.length)nonogramNew();};
  [byId('snakeBoard'),byId('sudokuBoard'),byId('nonogramBoard')].forEach(function(board){var count=0,last=0;board.addEventListener('click',function(){var now=Date.now(),finished=board.id==='snakeBoard'?snake.over:(board.id==='sudokuBoard'?sudoku.over:nonogram.won);if(!finished){count=0;last=now;return;}if(now-last>900)count=0;count++;last=now;if(count>=3){count=0;if(board.id==='snakeBoard')snakeNew();else if(board.id==='sudokuBoard')sudokuNew();else nonogramNew();}});});
  byId('snakeBoard').addEventListener('click',function(e){if(e.target===this)snakeTurn(1,0);});
}());
